FROM golang:1.22-alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN go mod download 

RUN go build -o recommendation.exe ./

FROM alpine AS release

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/recommendation ./

EXPOSE 8080
ENTRYPOINT ["./app.exe"]





