apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-app
  template:
    metadata:
      labels:
        app: recommendation-app
    spec:
      containers:
        - name: recommendation-container
          # Change the image with your image name in dockerhub repo
          image: recommendation:latest
          ports:
            - containerPort: 8080